apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: node-list-binding
subjects:
- kind: ServiceAccount
  name: default
  namespace: p-xurshid
roleRef:
  kind: ClusterRole
  name: node-list-role
  apiGroup: rbac.authorization.k8s.io
