apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-nginx
  namespace: p-xurshid
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: nginx
        image: nginx

