apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: myapp
  name: react-app-task6
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - image: visionindark/2048-react:v1-amd64
        name: react-app
        ports:
          - containerPort: 3000
