apiVersion: v1
kind: Pod
metadata:
  labels:
    app: myapp
  name: mynginx
spec:
  containers:
  - image: nginx
    name: nginx
    readinessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 30
      periodSeconds: 20
      timeoutSeconds: 10
  nodeName: node02

