apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: role-binding
subjects:
- kind: ServiceAccount
  name: admin
roleRef:
  kind: Role
  name: role
  apiGroup: rbac.authorization.k8s.io

